server: true
auto: true
markdown: kramdown
permalink: pretty
pygments: true
paginate: 10

kramdown:
  auto_ids: false

exclude:
  - config
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md

locale:
    test:
        en: "Hello"
        de: "Hallo"
