markdown: kramdown
permalink: pretty
relative_permalinks: false
pygments: true
paginate: 10
pagination_path: news/page:num

kramdown:
  auto_ids: false

exclude:
  - config
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md

assets:

  sources:
    - _assets

  compress:
    css:  sass
    js:   uglifier

  cachebust: none

locale:
    test:
        en: "Hello"
        de: "Hallo"
